### ISSUE TITLE
"List devices" response when no devices are available fails

### ISSUE THREAD

**Issue by claycooper** [bsatrom/particle-cloud-alexa-skill#11]
When trying any of the "list devices" requests and there are no online devices the response attempts to name the online devices.

**Comment by bsatrom** [comment]
Thanks @claycooper for reporting this! I noticed it in the logs last week and fixed it before release. Response now looks like this...

![screenshot 2018-04-13 08 53 13](https://user-images.githubusercontent.com/108356/38738640-478093c4-3ef8-11e8-82a6-060be36f846a.png)
